[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#00E5FF"
backgroundColor = "#0A0E17"
secondaryBackgroundColor = "#121826"
textColor = "#F0F3FA"
font = "sans serif"
